### ISSUE TITLE
Screen to Raspberry Pi Pinout

### ISSUE THREAD

**Issue by lboue** [fredrikbaberg/OctoPrint-SSD1306#4]
Hello,

Could you indicate on which Raspberry Pi pins it is necessary to connect the screen

**Comment by aragor88** [comment]
For my 3,3V PIOLED: SDA, SCL, GND and 3,3V, but don't works for me. I tested this OLED with arduino and OLED works well.

**Comment by fredrikbaberg** [comment]
Hi,
I'm using this display: https://learn.adafruit.com/adafruit-pioled-128x32-mini-oled-for-raspberry-pi/. The pinout is visible at https://pinout.xyz/ but it should at least be SDA and SCL.

Also, don't forget that you need to enable i2c, see e.g. https://community.octoprint.org/t/ssd1306-display-not-working/51243/2

**Comment by lboue** [comment]
Thanks @fredrikbaberg.
I create a PR #5 to complete documentation.
